const ICONS = {
  eyeInactive: require('../assets/icons/eyeInactive.png'),
  eyeActive: require('../assets/icons/eyeActive.png'),
  user: require('../assets/icons/user.png'),
  password: require('../assets/icons/password.png'),
  berandaActive: require('../assets/icons/berandaActive.png'),
  berandaInactive: require('../assets/icons/berandaInactive.png'),
  PRActive: require('../assets/icons/PRActive.png'),
  PRInactive: require('../assets/icons/PRInactive.png'),
  biayaActive: require('../assets/icons/biayaActive.png'),
  biayaInactive: require('../assets/icons/biayaInactive.png'),
  notifikasiActive: require('../assets/icons/notifikasiActive.png'),
  notifikasiInactive: require('../assets/icons/notifikasiInactive.png'),
  ulanganActive: require('../assets/icons/ulanganActive.png'),
  ulanganInactive: require('../assets/icons/ulanganInactive.png'),
  drawer: require('../assets/icons/drawer.png'),
  theme: require('../assets/icons/theme.png'),
  absenIcon: require('../assets/icons/absenIcon.png'),
  infoIcon: require('../assets/icons/infoIcon.png'),
  lowonganIcon: require('../assets/icons/lowonganIcon.png'),
  hollowCircle: require('../assets/icons/hollowCircle.png'),
  expand: require('../assets/icons/expand.png'),
  shrink: require('../assets/icons/shrink.png'),
  download: require('../assets/icons/download.png'),
  clock: require('../assets/icons/clock.png'),
  eyeWhite: require('../assets/icons/eyeWhite.png'),
  building: require('../assets/icons/building.png'),
  clockOrange: require('../assets/icons/clockOrange.png'),
  briefCase: require('../assets/icons/briefCase.png'),
  clockFill: require('../assets/icons/clockFill.png'),
  closeButton: require('../assets/icons/closeButton.png'),
}

export default ICONS